set_property PACKAGE_PIN J18 [get_ports txd]
set_property PACKAGE_PIN A18 [get_ports rst]
set_property IOSTANDARD LVCMOS33 [get_ports rst]
set_property IOSTANDARD LVCMOS33 [get_ports rxd]
set_property IOSTANDARD LVCMOS33 [get_ports txd]

set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]
set_property BITSTREAM.CONFIG.CONFIGRATE 33 [current_design]
set_property CONFIG_MODE SPIx4 [current_design]

set_property PACKAGE_PIN A17 [get_ports led0]
set_property IOSTANDARD LVCMOS33 [get_ports led0]

set_property PACKAGE_PIN J17 [get_ports rxd]

set_property IOSTANDARD LVCMOS33 [get_ports caurst_in]
set_property IOSTANDARD LVCMOS33 [get_ports COMACT]
set_property IOSTANDARD LVCMOS33 [get_ports ELSNCM]
set_property IOSTANDARD LVCMOS33 [get_ports KYRLS]
set_property IOSTANDARD LVCMOS33 [get_ports mainrs_in]
set_property IOSTANDARD LVCMOS33 [get_ports mkey1_in]
set_property IOSTANDARD LVCMOS33 [get_ports mkey2_in]
set_property IOSTANDARD LVCMOS33 [get_ports mkey3_in]
set_property IOSTANDARD LVCMOS33 [get_ports mkey4_in]
set_property IOSTANDARD LVCMOS33 [get_ports mkey5_in]
set_property IOSTANDARD LVCMOS33 [get_ports OPEROR]
set_property IOSTANDARD LVCMOS33 [get_ports RESTRT]
set_property IOSTANDARD LVCMOS33 [get_ports RLYB01]
set_property IOSTANDARD LVCMOS33 [get_ports RLYB02]
set_property IOSTANDARD LVCMOS33 [get_ports RLYB03]
set_property IOSTANDARD LVCMOS33 [get_ports RLYB04]
set_property IOSTANDARD LVCMOS33 [get_ports RLYB05]
set_property IOSTANDARD LVCMOS33 [get_ports RLYB06]
set_property IOSTANDARD LVCMOS33 [get_ports RLYB07]
set_property IOSTANDARD LVCMOS33 [get_ports RLYB08]
set_property IOSTANDARD LVCMOS33 [get_ports RLYB09]
set_property IOSTANDARD LVCMOS33 [get_ports RLYB10]
set_property IOSTANDARD LVCMOS33 [get_ports RLYB11]
set_property IOSTANDARD LVCMOS33 [get_ports RYWD12]
set_property IOSTANDARD LVCMOS33 [get_ports RYWD13]
set_property IOSTANDARD LVCMOS33 [get_ports RYWD14]
set_property IOSTANDARD LVCMOS33 [get_ports RYWD16]
set_property IOSTANDARD LVCMOS33 [get_ports sbybut_in]
set_property IOSTANDARD LVCMOS33 [get_ports SBYLIT]
set_property IOSTANDARD LVCMOS33 [get_ports TMPCAU]
set_property IOSTANDARD LVCMOS33 [get_ports UPLACT]
set_property IOSTANDARD LVCMOS33 [get_ports VNFLSH]
set_property PACKAGE_PIN L1 [get_ports caurst_in]
set_property PACKAGE_PIN P1 [get_ports COMACT]
set_property PACKAGE_PIN U5 [get_ports ELSNCM]
set_property PACKAGE_PIN N2 [get_ports KYRLS]
set_property PACKAGE_PIN W5 [get_ports mainrs_in]
set_property PACKAGE_PIN V5 [get_ports mkey1_in]
set_property PACKAGE_PIN L2 [get_ports mkey2_in]
set_property PACKAGE_PIN W4 [get_ports mkey3_in]
set_property PACKAGE_PIN A14 [get_ports mkey4_in]
set_property PACKAGE_PIN V3 [get_ports mkey5_in]
set_property PACKAGE_PIN J1 [get_ports OPEROR]
set_property PACKAGE_PIN N3 [get_ports RESTRT]
set_property PACKAGE_PIN A15 [get_ports RLYB01]
set_property PACKAGE_PIN B15 [get_ports RLYB02]
set_property PACKAGE_PIN V4 [get_ports RLYB03]
set_property PACKAGE_PIN K2 [get_ports RLYB04]
set_property PACKAGE_PIN T2 [get_ports RLYB05]
set_property PACKAGE_PIN N1 [get_ports RLYB06]
set_property PACKAGE_PIN U4 [get_ports RLYB07]
set_property PACKAGE_PIN R3 [get_ports RLYB08]
set_property PACKAGE_PIN M1 [get_ports RLYB09]
set_property PACKAGE_PIN U1 [get_ports RLYB10]
set_property PACKAGE_PIN U2 [get_ports RLYB11]
set_property PACKAGE_PIN P3 [get_ports RYWD12]
set_property PACKAGE_PIN V2 [get_ports RYWD13]
set_property PACKAGE_PIN T3 [get_ports RYWD14]
set_property PACKAGE_PIN M2 [get_ports RYWD16]
set_property PACKAGE_PIN J3 [get_ports sbybut_in]
set_property PACKAGE_PIN R2 [get_ports SBYLIT]
set_property PACKAGE_PIN W3 [get_ports TMPCAU]
set_property PACKAGE_PIN T1 [get_ports UPLACT]
set_property PACKAGE_PIN W2 [get_ports VNFLSH]
set_property PULLTYPE PULLDOWN [get_ports caurst_in]
set_property PULLTYPE PULLUP [get_ports mainrs_in]
set_property PULLTYPE PULLDOWN [get_ports mkey1_in]
set_property PULLTYPE PULLDOWN [get_ports mkey2_in]
set_property PULLTYPE PULLDOWN [get_ports mkey3_in]
set_property PULLTYPE PULLDOWN [get_ports mkey4_in]
set_property PULLTYPE PULLDOWN [get_ports mkey5_in]
set_property PULLTYPE PULLDOWN [get_ports sbybut_in]

set_property IOSTANDARD LVCMOS33 [get_ports upl0_in]
set_property IOSTANDARD LVCMOS33 [get_ports upl1_in]
set_property PACKAGE_PIN G17 [get_ports upl0_in]
set_property PACKAGE_PIN G19 [get_ports upl1_in]
set_property PULLTYPE PULLDOWN [get_ports upl0_in]
set_property PULLTYPE PULLDOWN [get_ports upl1_in]

set_property IOSTANDARD LVCMOS33 [get_ports dkbsnc_in]
set_property IOSTANDARD LVCMOS33 [get_ports DKDATA]
set_property IOSTANDARD LVCMOS33 [get_ports dkend_in]
set_property IOSTANDARD LVCMOS33 [get_ports dkstrt_in]
set_property PACKAGE_PIN H17 [get_ports dkstrt_in]
set_property PACKAGE_PIN H19 [get_ports dkbsnc_in]
set_property PACKAGE_PIN J19 [get_ports dkend_in]
set_property PACKAGE_PIN K18 [get_ports DKDATA]

set_property PULLTYPE PULLDOWN [get_ports dkbsnc_in]
set_property PULLTYPE PULLDOWN [get_ports dkend_in]
set_property PULLTYPE PULLDOWN [get_ports dkstrt_in]
