set_property -dict {PACKAGE_PIN W5 IOSTANDARD LVCMOS33 PULLTYPE PULLUP} [get_ports {mainrs_in}]
set_property -dict {PACKAGE_PIN V5 IOSTANDARD LVCMOS33 PULLTYPE PULLDOWN} [get_ports {mkey1_in}]
set_property -dict {PACKAGE_PIN L2 IOSTANDARD LVCMOS33 PULLTYPE PULLDOWN} [get_ports {mkey2_in}]
set_property -dict {PACKAGE_PIN W4 IOSTANDARD LVCMOS33 PULLTYPE PULLDOWN} [get_ports {mkey3_in}]
set_property -dict {PACKAGE_PIN A14 IOSTANDARD LVCMOS33 PULLTYPE PULLDOWN} [get_ports {mkey4_in}]
set_property -dict {PACKAGE_PIN V3 IOSTANDARD LVCMOS33 PULLTYPE PULLDOWN} [get_ports {mkey5_in}]
set_property -dict {PACKAGE_PIN L1 IOSTANDARD LVCMOS33 PULLTYPE PULLDOWN} [get_ports {caurst_in}]
set_property -dict {PACKAGE_PIN J3 IOSTANDARD LVCMOS33 PULLTYPE PULLDOWN} [get_ports {sbybut_in}]

set_property -dict {PACKAGE_PIN A15 IOSTANDARD LVCMOS33} [get_ports {RLYB01}]
set_property -dict {PACKAGE_PIN B15 IOSTANDARD LVCMOS33} [get_ports {RLYB02}]
set_property -dict {PACKAGE_PIN V4 IOSTANDARD LVCMOS33} [get_ports {RLYB03}]
set_property -dict {PACKAGE_PIN K2 IOSTANDARD LVCMOS33} [get_ports {RLYB04}]
set_property -dict {PACKAGE_PIN T2 IOSTANDARD LVCMOS33} [get_ports {RLYB05}]
set_property -dict {PACKAGE_PIN N1 IOSTANDARD LVCMOS33} [get_ports {RLYB06}]
set_property -dict {PACKAGE_PIN U4 IOSTANDARD LVCMOS33} [get_ports {RLYB07}]
set_property -dict {PACKAGE_PIN R3 IOSTANDARD LVCMOS33} [get_ports {RLYB08}]
set_property -dict {PACKAGE_PIN M1 IOSTANDARD LVCMOS33} [get_ports {RLYB09}]
set_property -dict {PACKAGE_PIN U1 IOSTANDARD LVCMOS33} [get_ports {RLYB10}]
set_property -dict {PACKAGE_PIN U2 IOSTANDARD LVCMOS33} [get_ports {RLYB11}]
set_property -dict {PACKAGE_PIN P3 IOSTANDARD LVCMOS33} [get_ports {RYWD12}]
set_property -dict {PACKAGE_PIN V2 IOSTANDARD LVCMOS33} [get_ports {RYWD13}]
set_property -dict {PACKAGE_PIN T3 IOSTANDARD LVCMOS33} [get_ports {RYWD14}]
set_property -dict {PACKAGE_PIN M2 IOSTANDARD LVCMOS33} [get_ports {RYWD16}]
set_property -dict {PACKAGE_PIN P1 IOSTANDARD LVCMOS33} [get_ports {COMACT}]
set_property -dict {PACKAGE_PIN U5 IOSTANDARD LVCMOS33} [get_ports {ELSNCM}]
set_property -dict {PACKAGE_PIN N2 IOSTANDARD LVCMOS33} [get_ports {KYRLS}]
set_property -dict {PACKAGE_PIN J1 IOSTANDARD LVCMOS33} [get_ports {OPEROR}]
set_property -dict {PACKAGE_PIN N3 IOSTANDARD LVCMOS33} [get_ports {RESTRT}]
set_property -dict {PACKAGE_PIN R2 IOSTANDARD LVCMOS33} [get_ports {SBYLIT}]
set_property -dict {PACKAGE_PIN W3 IOSTANDARD LVCMOS33} [get_ports {TMPCAU}]
set_property -dict {PACKAGE_PIN T1 IOSTANDARD LVCMOS33} [get_ports {UPLACT}]
set_property -dict {PACKAGE_PIN W2 IOSTANDARD LVCMOS33} [get_ports {VNFLSH}]
